package model

object Constantes {
    const val BOAS_VINDAS = "\nBOAS VINDAS À LANCHONETE FASTFOOD"
    const val ITEM_DESEJADO = "Digite o número correspondente ao item desejado: "
    const val OPCAO_DESEJADA = "Digite o número correspondente a opção desejada: "
    const val REFRIGERANTES = "REFRIGERANTES"
    const val SORVETES = "SORVETES"
    const val MOUSSES = "MOUSSES"
    const val SUCOS = "SUCOS"
    const val COMBO1 = "X-Burger, Refrigerante, Sorvete"
    const val COMBO2 = "X-Burger, Refrigerante, Mousse"
    const val COMBO3 = "X-Burger, Suco, Sorvete"
    const val COMBO4 = "X-Burger, Suco, Mousse"
    const val COMBO5 = "X-Salada, Refrigerante, Sorvete"
    const val COMBO6 = "X-Salada, Refrigerante, Mousse"
    const val COMBO7 = "X-Salada, Suco, Sorvete"
    const val COMBO8 = "X-Salada, Suco, Mousse"
    const val COMPRA_FINALIZADA = "\nCompra finalizada com sucesso!Boa refeição!"
    const val PAGAMENTO_DINHEIRO = "\nDigite o valor que irá pagar em dinheiro: "
    const val VALOR_MENOR = "\nO valor informado para o pagamento é menor que o total do pedido."
    const val VALOR_INVALIDO_QUANTIDADE = "\nFormato inválido! Para adicionar a quantidade, você deve informar o número correspondente."
    const val NUMERO_MAIOR_QUE_ZERO = "\nDigite um número maior que zero."
    const val QUANTIDADE = "\nDigite a quantidade de que deseja comprar de"
    const val NOVA_QUANTIDADE = "\nDigite a nova quantidade de"
    const val CODIGO_PRODUTO = "Digite o código do produto que deseja"
    const val OPCAO_INVALIDA = "\nOpção inválida, tente novamente."
    const val FORMATO_INVALIDO_OPCAO = "\nFormato inválido, para escolher uma opção, você deve informar o número dela."
    const val FORMATO_INVALIDO_ITEM = "\nFormato inválido, para escolher o item, você deve informar o número dele."
}